### ISSUE TITLE
Присутствие бургера

### ISSUE THREAD

**Issue by MikhailSklyarov1** [myakininayu/edu-client#11]
Сейчас бергер постоянно в шапке, но не всегда на странице есть навбар. Как по мне, навбар нужен только на страницах курсов. Поэтому на других страницах надо убрать и бургер. Или сместить его под шапку в навбар и тогда он (нав) будет тонкой вертикальной полоской, которая выдвигается.

**Comment by myakininayu** [comment]
А зачем бургер в навбар, если там есть стрелки?
![image](https://github.com/myakininayu/edu-client/assets/79317792/870c9555-9bc7-491c-a61c-c266e7f7ab20)

**Comment by MikhailSklyarov1** [comment]
Логично. Тогда можно убрать бургер и поместить туда лого. но тогда нужно сделать, чтобы при сворачивании дерева навбар тоже уменьшался.
