### ISSUE TITLE
Подвал сайта

### ISSUE THREAD

**Issue by MikhailSklyarov1** [myakininayu/edu-client#16]
Было бы неплохо сделать подвал с контактами. Возможно иконки-ссылки на соц. сети

**Comment by myakininayu** [comment]
На какие соц.сети? Насколько мне известно, у Юнита есть свой сайт + группа в вк, которая не обновляется

**Comment by MikhailSklyarov1** [comment]
> На какие соц.сети? Насколько мне известно, у Юнита есть свой сайт + группа в вк, которая не обновляется

Ну да, можно тот сайт и вк. Потом еще что-нибудь добавим

**Comment by myakininayu** [comment]
Контакты в футере навели меня на одну мысль. Предлагаю еще добавить информацию о преподавателях. Можно на главной странице, под новостями. Если тебе идея понравится, я сама добавлю в issue.

**Comment by MikhailSklyarov1** [comment]
> Контакты в футере навели меня на одну мысль. Предлагаю еще добавить информацию о преподавателях. Можно на главной странице, под новостями. Если тебе идея понравится, я сама добавлю в issue.

Я этот сайт иначе представлял - как инструмент, а не визитку Юнита. Но если есть желание, то я не против
