### ISSUE TITLE
В редактор кода можно добавить кнопку для очистки кода 

### ISSUE THREAD

**Issue by MikhailSklyarov1** [myakininayu/edu-client#19]
По аналогии с копированием кода. Иконки должны быть выстроены в колонку справа

**Comment by myakininayu** [comment]
Сделала очищение, то кнопки располагаются в строку
![image](https://github.com/myakininayu/edu-client/assets/79317792/6c8314dd-1143-40bc-ae46-cc34de3e294b)

**Comment by MikhailSklyarov1** [comment]
> Сделала очищение, но кнопки располагаются в строку ![image](https://user-images.githubusercontent.com/79317792/263217098-6c8314dd-1143-40bc-ae46-cc34de3e294b.png)

![image](https://github.com/myakininayu/edu-client/assets/78589614/d3763aa3-9529-4c5d-8918-3b25086e1033)
Тут некликабельная зона - хорошо ли это?  И если горизонтально сделать, то эта зона  больше съест пространства для кода

**Comment by myakininayu** [comment]
Ладно, пусть будет вертикально
