### ISSUE TITLE
Кажется, отступ контента от левого края нужно сделать сильно больше. Или справа какую-то плашку придумать. А то сейчас все находится слева

### ISSUE THREAD

**Issue by MikhailSklyarov1** [myakininayu/edu-client#20]

**Comment by myakininayu** [comment]
![image](https://github.com/myakininayu/edu-client/assets/79317792/09eef4b7-3004-401e-a3d6-6170735ff213)

**Comment by MikhailSklyarov1** [comment]
> ![image](https://user-images.githubusercontent.com/79317792/263217858-09eef4b7-3004-401e-a3d6-6170735ff213.png)

Идея неплохая, под это можно сделать компонент. Но я не только про редактор говорил, а про вест контент. Странно смотрится, что все (картинки, редактор, видео) слева. Слишком широкое поле для контента

**Comment by myakininayu** [comment]
Тогда лучше отступы. Не надо визуальный мусор прикручивать
